server:
  port: 2222

spring:
  application:
    name: house-service
  cloud:
    config:
      uri: http://localhost:9090
    
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/