server:
  port: 9090
  
security:
  basic:
    enabled: false
    
spring:
  application:
    name: configuration-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native: 
          searchLocations: classpath:/common-config/application.properties
      
  