server:
  port: 9090

security:
  basic:
    enabled: false

spring:
  application:
    name: oha-configuration-service
  profiles:
    active: native
  # Specify configs location
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/common-config          
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
    # trying registry to eureka server
    registry-fetch-interval-seconds: 5