server:
  port: 9090
  
security:
  basic:
    enabled: false
    
spring:
  application:
    name: configuration-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/common-config
          
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
      
  